# Generated by Django 5.0.3 on 2024-03-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='letting',
            table='letting',
        ),
    ]
