  # on master push or pull request
# définir les variables d'environnement
# build image docker
# push l'image docker sur dockerhub
# pull l'image sur AWS

name: master-push
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read

jobs:
  name: Push Docker image to Docker Hub
  runs-on: ubuntu-latest
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ryad364/projet-oc-letting

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: push Docker image in AWS 
      uses: aws ecr get-login-password --region region | docker login AWS_USERNAME AWS AWS_PASSWORD-stdin aws_account_id.dkr.ecr.region.amazonaws.com

  